name: Upload Website to S3
on: 
  push:
    branches:
    - frontend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v1
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secretes.AWS_REGION }}
        
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./ s3://${{ secretes.AWS_S3_BUCKET }} --delete --exclude ".*"
      
    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} --paths "/*"

name: Publish SAM to AWS
on:
  push:
    branches:
      - backend
jobs:
  build-deploy:
    name: Package 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Python unit test
    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

 #   - name: Install dependencies
 #     run: |
 #       python -m pip install --upgrade pip
 #       pip install -r Lambda/requirements.txt
 #       pip install moto boto3
 #   - name: Unittest visitor counter Lambda
 #     run: python Lambda/pythontest.py
    
    # SAM
    - name: SAM Build
      uses: aws-actions/setup-sam@v1
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

      # SAM build 
      - run: sam build --use-container
    
      # SAM deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --template-file samtemplate.yaml --stack-name ${{ secrets.STACK_NAME }} --s3-bucket ${{ secrets.AWS_SAM_S3_BUCKET }} --region ${{ secrets.AWS_REGION }} --capabilities CAPABILITY_IAM
